django_proiect/proiect/aplicatie1/urls.py
from django.urls import path
from aplicatie1 import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationsView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationsView.as_view(), name='adaugare'),
    path('<int:pk>/update/', views.UpdateLocationsView.as_view(), name='modificare'),
    path('<int:pk>/delete/', views.delete_location, name='stergere'),
    path('<int:pk>/activate/', views.activate_location, name='activare'),

    path('start_timesheet', views.start_timesheet, name='start_pontaj'),
    path('stop_timesheet', views.stop_timesheet, name='stop_pontaj'),
]

django_proiect/proiect/myapi/urls.py
from django.urls import include, path
from rest_framework import routers

from myapi import views

router = routers.DefaultRouter()
router.register('location', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls))
]

django_proiect/proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('locations/', include('aplicatie1.urls')),
    path('', include('django.contrib.auth.urls'), {'next': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('userprofile/', include('userprofile.urls')),
    path('api/', include('myapi.urls')),
]

django_proiect/proiect/userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('new_account/', views.CreateNewAccount.as_view(), name='utilizator_nou')
]

django_proiect/proiect/templates/base.html
{% load i18n %}
<html>
    <head>
{#        DTL - django template tag#}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            <div class="row>">
                <nav>
                    {% if request.user.is_authenticated and request.path != '/' %}
                        <span style="color:blue"> Hi, {{ request.user.username|upper }}! </span>
                    {% endif %}
                    <a class="btn" href="/admin">Admin</a>
                    {% if request.user.is_authenticated and request.path != '/' %}
                        <a class="btn" href="{% url 'locations:lista_locatii' %}">Locatii</a>
                        <a class="btn btn-sm btn-danger" href="{% url 'logout' %}">Logout</a>
                        {% if ready_to_work %}
                            <a class="btn btn-sm btn-success" href="{% url 'locations:start_pontaj' %}">Pornire Pontaj</a>
                        {% else %}
                            <a class="btn btn-sm btn-danger" href="{% url 'locations:stop_pontaj' %}">Stop Pontaj</a>
                        {% endif %}
                        <a class='btn btn-sm btn-primary' href="{% url 'userprofile:utilizator_nou' %}">New Account</a>
                    {% endif %}
                </nav>
            </div>
        </div>
        {% block title %}

        {% endblock %}
    </body>

    <footer class="footer">
{#        <div>#}
            <p style="margin-top: 30%" class="copyright pull-left">© {% now 'Y' %} Scoala Informala de IT</p>
{#        </div>#}
    </footer>
</html>