django_proiect/proiect/aplicatie1/urls.py
from django.urls import path
from aplicatie1 import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationsView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationsView.as_view(), name='adaugare'),
    path('<int:pk>/update/', views.UpdateLocationsView.as_view(), name='modificare'),
    path('<int:pk>/delete/', views.delete_location, name='stergere'),
    path('<int:pk>/activate/', views.activate_location, name='activare'),

    path('start_timesheet', views.start_timesheet, name='start_pontaj'),
    path('stop_timesheet', views.stop_timesheet, name='stop_pontaj'),
]

django_proiect/proiect/myapi/urls.py
from django.urls import include, path
from rest_framework import routers

from myapi import views

router = routers.DefaultRouter()
router.register('location', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls))
]

django_proiect/proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('locations/', include('aplicatie1.urls')),
    path('', include('django.contrib.auth.urls'), {'next': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('userprofile/', include('userprofile.urls')),
    path('api/', include('myapi.urls')),
]

django_proiect/proiect/aplicatie1/models.py
from django.db import models


class Location(models.Model):  # aplicatie1_location
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=90)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.city} -> {self.country}'


class Pontaj(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True)

    def __str__(self):
        return f'{self.user} started at: {self.start_date}'


class Logs(models.Model):
    action_choices = (('created', 'created'),
                      ('updated', 'updated'),
                      ('refresh', 'refresh'))

    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    action = models.CharField(max_length=10, choices=action_choices)
    url = models.CharField(max_length=100)

django_proiect/proiect/aplicatie1/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse
from aplicatie1.models import Location, Pontaj, Logs


# CreateView -> adaugarea datelor in baza de date (instante noi)
# DetailView -> vizualizarea datelor unei instante din baza de date (furnizez pk)
# ListView -> vizualizarea datelor mai multor instante din baza de date
# UpdateView -> modificarea datelor din baza de date (furnizez pk)
# DeleteView -> stergerea datelor din baza de date (furnizez pk)

class LocationsView(LoginRequiredMixin, ListView):
    model = Location
    template_name = 'aplicatie1/locations_index.html'


class CreateLocationsView(LoginRequiredMixin, CreateView):
    model = Location
    template_name = 'aplicatie1/locations_form.html'
    fields = ['city', 'country']

    def get_success_url(self):
        return reverse('locations:lista_locatii')

    # def get_context_data(self, **kwargs):
    #     context = super(CreateLocationsView, self).get_context_data(**kwargs)
    #     context['gigel'] = Logs.objects.get(id=1)
    #     return context


class UpdateLocationsView(LoginRequiredMixin, UpdateView):
    model = Location
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


@login_required
def delete_location(request, pk):
    """
    SQL native query: SELECT id, city FROM aplicatie1_location WHERE id=1
    Django query: Location.objects.get(id=1).id

    model.objects.get(coloana1=val1, coloana2=val2) -> returneaza o singura inregistrare
                -> daca nu exista inregistrarea cautata in db sau exista mai multe inregistrari in db care contin
                aceeasi valoare a parametrilor din get, va returna eroare (recomandat este sa fie folosit ca si param. id-ul)
                -> avand in vedere ca returneaza o singura inregistrare (obiect) putem sa accesam direct atributul
                (proprietatea, field-ul din db): model.objects.get(id=1).city
    models.object.filter(coloana1=val1, coloana2=val2) -> returneaza 1 sau mai multe inregistrari
                -> ca sa accesez atributele (field-urile) pot sa:
                    - fie iteram prin rezultate
                    - fie sa scriu model.objects.filter().values()
                    - fie sa scriu model.objects.filter().values_list('city')
    @type request:
    @param pk:
    """
    # folosind get
    # instance_object = Location.objects.get(id=pk)
    # if instance_object.active:
    #     instance_object.active = False
    #     instance_object.save()

    # folsind filter
    Location.objects.filter(id=pk).update(active=False)
    return redirect('locations:lista_locatii')


@login_required
def activate_location(request, pk):
    Location.objects.filter(id=pk).update(active=True)
    return redirect('locations:lista_locatii')


@login_required
def start_timesheet(request):
    # new_instance = Pontaj()
    # new_instance.start_date = datetime.datetime.now()
    # new_instance.user_id = request.user.id
    # new_instance.save()
    Pontaj.objects.create(user_id=request.user.id, start_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def stop_timesheet(request):
    Pontaj.objects.filter(user_id=request.user.id, end_date=None).update(end_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

django_proiect/proiect/templates/aplicatie1/locations_form.html
{% extends 'base.html' %}
{% block title %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }} {{ field.errors }}
        {% endfor %}
        <button type="submit" class="btn btn-success">Salveaza</button>
        <p>{{ gigel.url }}  {{ gigel.action }}</p>
    </form>
{% endblock %}

django_proiect/proiect/templates/aplicatie1/locations_index.html
{% extends 'base.html' %}
{% block title %}
    <a class="btn btn-primary" href="{% url 'locations:adaugare' %}">Adauga inregistrare</a>
    <table class="table">
        <thead>
            <tr>
                <th>Index</th>
                <th>City</th>
                <th>Country</th>
                <th>Active</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in location_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.city }}</td>
                    <td>{{ item.country }}</td>
                    {% if item.active %}
                        <td>Activ</td>
                    {% else %}
                        <td>Inactiv</td>
                    {% endif %}
{#                    <td>{{ item.active }}</td>#}
                    <td>
                        <a class="btn btn-warning" href="{% url 'locations:modificare' item.id %}">Editare</a>
                        {% if item.active %}
                            <a class="btn btn-danger" href="{% url 'locations:stergere' item.id %}">Stergere</a>
                        {% else %}
                            <a class="btn btn-info" href="{% url 'locations:activare' item.id %}">Activare</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}